# Generated by Django 4.2.1 on 2023-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationtypes',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Like', 'Like'), ('Follow', 'Follow')], max_length=20),
        ),
    ]
