# Generated by Django 4.2 on 2023-05-13 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blog_slug_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
