# Generated by Django 4.2 on 2023-05-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_blog_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_blogs', to='blog.category'),
        ),
    ]
